# Generated by Django 4.1.4 on 2023-02-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_colorevent_alter_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ColorEvent',
        ),
    ]
